# Generated by Django 3.2 on 2022-12-29 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_email_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email', to='User.user', to_field='username'),
        ),
    ]
